version: '2'

services:

  rabbitmq:
    ports:
      - 5672:5672

  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry

  gateway:
    build: gateway

  employee-service:
    build: employee-service
    ports:
      - 6000:6000

  monitoring:
    build: monitoring