version: '2'

services:

  rabbitmq:
    ports:
      - 5672:5672

  config-service:
    build: config-service
    ports:
      - 8888:8888

  registry-service:
    build: registry-service

  gateway-ui:
    build: gateway-ui

  employee-service:
    build: employee-service
    ports:
      - 6000:6000

  employee-service-mongodb:
    build: mongodb
    ports:
      - 26000:27017

  monitoring-service:
    build: monitoring-service