version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  config:
    image: victorsalaun/skillsbrowser-config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    image: victorsalaun/skillsbrowser-registry
    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    image: victorsalaun/skillsbrowser-gateway
    restart: always
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  employee-service:
    image: victorsalaun/skillsbrowser-employee-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  monitoring:
    image: victorsalaun/skillsbrowser-monitoring
    restart: always
    ports:
      - 9000:8080
      - 8989:8989
    logging:
      options:
        max-size: "10m"
        max-file: "10"