spring:
  application:
    name: REGISTRY-SERVICE

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  datacenter: ${DATACENTER}
  environment: ${ENV:test}
  instance:
    hostname: ${HOSTNAME}
    prefer-ip-address: true
  region: ${REGION} # not working


server:
  port: ${PORT:8761}